### ISSUE TITLE
Only PHP 7?

### ISSUE THREAD

**Issue by visualcookie** [xandros15/SlimPagination#3]
Does this work with PHP 6.x too? Or are you using anything special thats only available with PHP 7?

**Comment by xandros15** [comment]
Nope because this project is using
- scalar type declaration;
- return type declarations; (somewhere missing)

Sorry, but I want to force people to use PHP 7.

You can pull and delete all declarations and should be works, but I'm not sure.

Also, why do you use PHP 6 instead of 5?

**Comment by visualcookie** [comment]
Oh, I'm not. But PHP 5.6 is PHP 6 for me, since there was no actual version 6. Thanks for your response though. Have to look if I'm able to upgrade the servers at the company.
